[project]
name = "fastapi-workout-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.136.3",
    "imagekitio>=5.5.2",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.13.0",
    "pymongo>=4.17.0",
    "pytest>=9.0.3",
    "sqlalchemy>=2.0.50",
]
