apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: omarsa999/workout-app
        
        envFrom:
          - secretRef:
              name: app-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-app
spec:
  selector:
    app: fastapi-app
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30008
    protocol: TCP